---
- hosts: nahtavyydet

  sudo: True

  vars:

    - remove_old_directory: False

  tasks:

    - name: Unpackage theme
      shell: "tar xjf dist.tar.bz2"
      args:
        chdir: "/nahtavyydet"

    - name: Remove existing theme contents from container
      docker:
        image: busybox
        command: "/bin/sh -c 'rm -rf /var/www/html/wp-content/themes/nahtavyydet/*'"
        volumes_from: nahtavyydet
        state: running

    - name: Add theme to container
      docker:
        image: busybox
        command: "/bin/sh -c 'cp -r /nahtavyydet /var/www/html/wp-content/themes/'"
        volumes:
          - "/nahtavyydet/dist:/nahtavyydet"
        volumes_from: nahtavyydet
        state: running

    - name: Remove cloned directory
      file:
        path: "/nahtavyydet/theme"
        state: absent
